version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ssq
      POSTGRES_PASSWORD: ScR26011161
      POSTGRES_DB: petproject
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssq -d petproject"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8002" 
    volumes:
      - ./config.json:/app/config.json 

volumes:
  pg_data: 
