services:
  redis:
    image: redis:latest
    platform: linux/arm64
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8003:8003"
    volumes:
      - ./config.json:/app/config.json
